name: Build Debug Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Build for android
        run: ./build.sh -a

      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

